version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: springboot_app
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/mi_base_de_datos?authSource=admin
    networks:
      - app_network

  mongodb:  # 👈 Ahora está dentro de `services`
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mi_base_de_datos
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
