# Usar una imagen base de Java 17
FROM eclipse-temurin:17-jdk-alpine

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el JAR desde la carpeta target en la raíz del proyecto
COPY target/backend-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto 8082
EXPOSE 8082

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
